name: Master

on: 
   push:
     branches : 
       - master

jobs:
  #    Windows-Chicken:
  #    runs-on: windows-latest

  #    steps:
  #    - name: Checkout
  #      uses: actions/checkout@master

  #    - name: use Setup-Scheme
  #      uses: guenchi/setup-scheme@master
  #      with:
  #     implementation: chicken

  # - run: chicken-install -s pstk r7rs
  # - run: csc -vvv -gui -static -o tf2cd.exe tf2cd.scm

  Linux-Chicken:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chicken

    - run: chicken-install -s pstk r7rs
    - run: pwd
    - run: csc -vvv -gui -static -o /tmp/tf2cd tf2cd.scm

    - name: "production artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: tf2cd
        path: /tmp
