            - name: Setup Scheme
  # You may pin to the exact commit or the version.
  # uses: guenchi/setup-scheme@5be14b53879a5198ebd9f72073f378a47b75f3d8
  uses: guenchi/setup-scheme@0.0.8
  with:
    # Implementation of Scheme to use
    implementation: chicken
    # Version range or exact version of Scheme to use
    version: # optional
    # Option Specific
    option: # optional
