name: Master

on:
   push:
     branches :
       - master

jobs:
  Windows-Chicken:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use Setup-Scheme
        uses: guenchi/setup-scheme@master
        with:
          implementation: chicken

      - run: chicken-install -s pstk
      - run: cp C:/tools/chicken/share/chicken/chicken.rc.o C:/tools/chicken/share/chicken/chicken.rc.obj
      - run: csc -vvv -gui -static -o tf2cd.exe tf2cd.scm
